electrode: 1
date: 20221013
block: 12
new_order: True
align_vep: False
adjust_alignment: True
vep_offset: 0
automate_offset: 0
manual_trough_time: 0.2999
run_fft: False
max_frequency: 120
min_frequency: 0
fft_channel: 5
truncate_trials: False
trials2analyze: 100
trial_size: 1.2
notch_filter: 1
filter_bandwidth: 5
cleanup: True
college_park: True
